# Generated by Django 5.1.3 on 2024-11-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_pro_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_id',
            field=models.IntegerField(),
        ),
    ]
